# This doesn't work well. For instance, the patch generated for deces_1997.csv is very big
# compared to the one generated by the diff command.
# It doesn't work with files that have inconsistent encoding.

from difflib import unified_diff
from pathlib import Path

renamed_csv_folder = Path('01-renamed/csv')
corrected_csv_folder = Path('02-corrected/csv')
patches_folder = Path('patches')

renamed_csv_files = renamed_csv_folder.glob('*.csv')

for renamed_csv_file in renamed_csv_files:
    corrected_csv_file = corrected_csv_folder / renamed_csv_file.name
    patch_file = patches_folder / (renamed_csv_file.name + '.patch')
    
    with open(renamed_csv_file, 'r', encoding='utf-8') as f1, open(corrected_csv_file, 'r', encoding='utf-8') as f2:
        with open(patch_file, 'w', encoding='utf-8') as f3:
            f3.writelines(unified_diff(f1.readlines(), f2.readlines(), fromfile=str(renamed_csv_file), tofile=str(corrected_csv_file), n=0))