#!/usr/bin/env bash

# This is not multiplatform... but at least it is fast!

shopt -s nullglob

source_csv_folder="./00-source/csv"
corrected_csv_folder="./01-corrected/csv"
patches_folder="./patches"

for source_csv_file in $source_csv_folder/*.csv
do
  base_name="$(basename -- $source_csv_file)"
  corrected_csv_file=$corrected_csv_folder/$base_name
  
  echo "Creating patch FROM $source_csv_file TO $corrected_csv_file ..."
  diff -Nar -U 0 $source_csv_file $corrected_csv_file > $patches_folder/$base_name.patch
done
