#!/usr/bin/env bash

# This is not multiplatform... but at least it is fast!
# git patch is slow as f.

shopt -s nullglob

corrected_csv_folder="./01-corrected/csv"
patches_folder="./patches"

for patch_file in $patches_folder/*.patch
do
  base_name="$(basename -- $patch_file .patch)"
  corrected_file=$corrected_csv_folder/$base_name

  patch $corrected_file < $patch_file
done
